language: php

sudo: false

services:
  - redis-server

matrix:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4

install:
  - make dependencies

script:
  - make test
  - make qa
  - make license
  - make changelog
