language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

services:
  - redis-server

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1

install:
  - composer install

script: vendor/bin/phpunit
