language: php

sudo: false

services:
  - redis-server

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2

install:
  - composer install

script: vendor/bin/phpunit
